#-------------------------------
# General Site Settings

title: Jinho's Page
logo: 
author: themefisher
description: this is meta description
email: jin-ho@pusan.ac.kr
phone: +82-10-5798-7949
address: Jangjeon-dong, Busan
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Research highlight, link: '/blog'}
- {name: Publications, link: '/publication'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Jinho <br> Ph.D. student

social:
#- {icon: "ti-facebook", link: "https://www.naver.com"}
- {icon: "ti-instagram", link: "https://www.instagram.com/jinhobyeon/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  My name is Jinho Byun. I'm a Ph.D. student in Pusan National University. My research intereset is Oxide Interfaces.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: DFT code(VASP), color: '#fdb157', value: '90%'}
- {name: Programming(Python), color: '#9473e6', value: '60%'}
- {name: Machine Learning, color: '#bdecf6', value: '40%'}
- {name: Cooking, color: '#ffbcaa', value: '50%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Bachelor of Science, date: '2017', organization: 'Pusan Natioinal University'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: UI Design,
    icon: ti-palette,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }
- {
    name: UX Design,
    icon: ti-vector,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: true # Add true to select section
  }
- {
    name: Interaction Design,
    icon: ti-panel,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: jin-ho@pusan.ac.kr


publications:
  - year : 2021
    list :
    - author: "YI Kim, M Jeong, J Byun, S-H Yang, W Choi, W-S Jang, J Jang, K Lee, Y Kim, J Lee, E Lee, Y-M Kim"
      title : "Atomic-scale identification of invisible cation vacancies at an oxide homointerface"
      journal : "Materials Today Physics 16, 100302"
      link  : "https://www.sciencedirect.com/science/article/pii/S2542529320301267"

  - year : 2020
    list :
    - author: J Jo, J Byun, J Lee, D Choe, I Oh, J Park, MJ Jin, J Lee, JW Yoo
      title : Emergence of Multispinterface and Antiferromagnetic Molecular Exchange Bias via Molecular Stacking on a Ferromagnetic Film
      journal : Advanced Functional Materials 30 (11), 1908499
      link  : "https://onlinelibrary.wiley.com/doi/abs/10.1002/adfm.201908499"

  - year : 2018
    list :
    - author: SJ Kwon, BM Jung, T Kim, J Byun, J Lee, SB Lee, UH Choi
      title : Influence of Al2O3 Nanowires on Ion Transport in Nanocomposite Solid Polymer Electrolytes
      journal : Macromolecules 51 (24), 10194-10201
      link  : "https://pubs.acs.org/doi/abs/10.1021/acs.macromol.8b01603"

    - author: J Jo, J Byun, I Oh, J Park, MJ Jin, BC Min, J Lee, JW Yoo
      title : Molecular tunability of magnetic exchange bias and asymmetrical magnetotransport in metalloporphyrin/Co hybrid bilayers
      journal : ACS nano 13 (1), 894-903
      link  : "https://pubs.acs.org/doi/abs/10.1021/acsnano.8b08689"

  - year : 2017
    list :
    - author: Trinh Thi Ly, Ganbat Duvjir, Taewon Min, Jinho Byun, Taehoon Kim, Mahmoud M Saad, Nguyen Thi Minh Hai, Sunglae Cho, Jaekwang Lee, Jungdae Kim
      title : Atomistic study of the alloying behavior of crystalline SnSe1−xSx
      journal : Physical Chemistry Chemical Physics 19 (32), 21648-21654
      link  : "https://pubs.rsc.org/en/content/articlehtml/2017/cp/c7cp03481d"